[build]
target = "index.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/"
# Brotli compression for wasm
compress = ["br", "gzip"]

[serve]
# The address to serve on.
addr = "127.0.0.1"
# The port to serve on.
port = 3080
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = false
